"""
Test launch file for the suites generated by ros2_test_compose.

A thin wrapper around gen_traj.launch.py: same nodes, same URDF/descriptor
resolution paths, with four arguments pinned so the suites are fast,
deterministic and hardware-free:

- gui:=false             drops RViz (avoids ~15s of SIGINT->SIGTERM->SIGKILL per
                          suite, and the -9/-6 exit codes that pollute
                          assertExitCodes)
- voxel_size:=0.05        pinned rather than inherited. It matches the
                          production default, but test_object.yaml (case 04)
                          asserts an exact voxel count, so the value is stated
                          here instead of tracking whatever production picks.
- mapper_extent_xyz       [2.0, 2.0, 2.0], which at 0.05 m gives a 40^3 = 64000
                          voxel grid -- the count case 04 expects
- robot:=emulator         no real Doosan arm is present under test
"""

import os

from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch.actions import IncludeLaunchDescription
from launch.launch_description_sources import PythonLaunchDescriptionSource


def generate_launch_description():
    curobo_ros_launch_dir = os.path.join(
        get_package_share_directory('curobo_ros'), 'launch')

    return LaunchDescription([
        IncludeLaunchDescription(
            PythonLaunchDescriptionSource(
                os.path.join(curobo_ros_launch_dir, 'gen_traj.launch.py')
            ),
            launch_arguments={
                'gui': 'false',
                'voxel_size': '0.05',
                'mapper_extent_xyz': '[2.0, 2.0, 2.0]',
                'robot': 'emulator',
            }.items()
        ),
    ])
