# Test kinematics services (FK and IK)

package: curobo_ros
environment:
  nodes:
    - package: curobo_ros
      executable: curobo_ik
      name: curobo_ik
  startup_delay: 10.0

tests:
  # - name: "01 FK valid joints"
  #   service: "/curobo_ik/fk_compute"
  #   type: curobo_msgs/srv/Fk
  #   data:
  #     joint_states:
  #       - name: ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']
  #         position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
  #   expect: {}

  - name: "02 IK valid pose"
    service: "/curobo_ik/ik_pose"
    type: curobo_msgs/srv/Ik
    data:
      pose:
        position: {x: 0.5, y: 0.0, z: 0.5}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
    expect: {success: True}

  - name: "03 IK invalid pose"
    service: "/curobo_ik/ik_pose"
    type: curobo_msgs/srv/Ik
    data:
      pose:
        position: {x: 10.0, y: 10.0, z: 10.0}
        orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
    expect: {success: False}
